title: Aldo Tomás Orduña Fabila
logo: /assets/img/perfil.PNG
description: Ciencia de Datos | Ingeniero Industrial | Planeación de la Demanda | 📍Hidalgo, México.
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme
