title: Aldo Tomás Orduña Fabila
description: Ingeniero Industrial | Ciencia de Datos | Planeación de la Demanda
remote_theme: pages-themes/minimal@v0.2.0
google_analytics: # Deja vacío por ahora si no tienes
show_downloads: false
logo: /assets/img/perfil.jpg
