title: Aldo Tomás Orduña Fabila
logo: /assets/img/perfil.png # Asegúrate de que el nombre coincida con tu archivo
description: Ciencia de Datos | Ingeniero Industrial | Planeación de la Demanda | 📍Hidalgo, México.
remote_theme: pages-themes/minimal@v0.2.0
google_analytics: # Deja vacío por ahora si no tienes
show_downloads: false
plugins:
- jekyll-remote-theme
